apiVersion: v1
kind: Pod
metadata:
  name: probe-readiness-httpget
  labels:
    app: nginx
spec:
  containers:
    - name: probe-readiness-httpget
      image: nginx:mainline
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
      readinessProbe:
        httpGet:
          port: http
          path: /nofount
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          port: http
          path: /
        initialDelaySeconds: 5
        periodSeconds: 2
  restartPolicy: Always
