apiVersion: v1
kind: Pod
metadata:
  name: probe-liveness-http-named-port
  labels:
    app: nginx
spec:
  containers:
    - name: probe-liveness-http-named-port
      image: nginx:mainline
      ports:
        - containerPort: 80
          name: default
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          port: default
          path: /notfound
          httpHeaders:
            - name: Version
              value: v1
        initialDelaySeconds: 5
        periodSeconds: 5
  restartPolicy: Always
