apiVersion: v1
kind: Pod
metadata:
  name: probe-startup-httpget
  labels:
    app: nginx
spec:
  containers:
    - name: probe-startup-httpget
      image: nginx:mainline
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
      startupProbe:
        httpGet:
          port: http
          path: /
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 5
      livenessProbe:
        httpGet:
          port: http
          path: /notfount
        periodSeconds: 2
        failureThreshold: 3
  restartPolicy: Always
