apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_HOST: localhost
  DATABASE_PORT: "5432"
  DATABASE_USER: crud_apps
  DATABASE_PASSWORD: crud_apps_secret
  DATABASE_NAME: crud_apps
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: database
      image: postgres
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PASSWORD
              name: db-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: db-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: db-config
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  containers:
    - name: webserver
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: db-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: db-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: db-config
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PASSWORD
              name: db-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: db-config
  restartPolicy: Always


