apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-cpu-limit-only
  labels:
    app: pod-resource-cpu-limit-only
spec:
  containers:
    - name: pod-resource-cpu-limit-only
      image: vish/stress
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1000m"
      args: [ "-cpus=2" ]
  restartPolicy: Always
