apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-memory-more-than-limit
  labels:
    app: pod-resource-memory-more-than-limit
spec:
  containers:
    - name: pod-resource-memory-more-than-limit
      image: polinux/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command:
        - stress
      args: [ "--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1" ]
  restartPolicy: Never
