apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-req-and-limit
  labels:
    app: pod-resource-req-and-limit
spec:
  containers:
    - name: pod-resource-req-and-limit
      image: nginx:mainline
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "1"
  restartPolicy: Always
