apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-cpu-req-limit
  labels:
    app: pod-resource-cpu-req-limit
spec:
  containers:
    - name: pod-resource-cpu-req-limit
      image: vish/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "500m"
        limits:
          cpu: "1.5"
      args: [ "-cpus=2" ]
  restartPolicy: Always
