apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-memory-more-than-node1
  labels:
    app: pod-resource-memory-more-than-node
spec:
  containers:
    - name: container1
      image: polinux/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      command:
        - stress
      args: [ "--vm", "1", "--vm-bytes", "400M", "--vm-hang", "1" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-memory-more-than-node2
  labels:
    app: pod-resource-memory-more-than-node
spec:
  containers:
    - name: container2
      image: polinux/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      command:
        - stress
      args: [ "--vm", "1", "--vm-bytes", "400M", "--vm-hang", "1" ]
  restartPolicy: Never
