apiVersion: v1
kind: Pod
metadata:
  name: pod-env-secret-envfrom
  labels:
    app: postgresql
spec:
  containers:
    - name: pod-env-secret-envfrom
      image: postgres
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_DB
          value: crud_apps
      envFrom:
        - secretRef:
            name: db-cred
            optional: false
  restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: db-cred
data:
  POSTGRES_PASSWORD: Y3J1ZF9hcHBzX3NlY3JldA==
  POSTGRES_USER: Y3J1ZF9hcHBz
