---
apiVersion: v1
kind: Secret
metadata:
  name: db-cred
data:
  DB_PASSWORD: Y3J1ZF9hcHBzX3NlY3JldA==
  DB_USER: Y3J1ZF9hcHBz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: crud_apps
  DB_HOST: localhost
  DB_PORT: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: database
      image: postgres
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-cred
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: db-cred
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: db-config
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  containers:
    - name: webserver
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: db-cred
            optional: false
        - configMapRef:
            name: db-config
            optional: false
  restartPolicy: Always

