apiVersion: v1
kind: Pod
metadata:
  name: pod-command-args
  labels:
    app: os-alpine
spec:
  containers:
    - name: pod-command-args
      image: alpine
      imagePullPolicy: IfNotPresent
      command: [ "echo" ]
      args:
        - 'Hai saya sedang belajar kubernetes!'
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-command-args2
  labels:
    app: os-ubuntu
spec:
  containers:
    - name: pod-command-args2
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: [ "uname" ]
      args:
        - "-a"
  restartPolicy: OnFailure
