apiVersion: v1
kind: Pod
metadata:
  name: pod-image-pull-secret
  labels:
    app: nginx
spec:
  containers:
    - name: pod-image-pull-secret
      image: dimmaryanto93/private-kubernetes-cource
      imagePullPolicy: Always
  imagePullSecrets:
    - name: dockerhub
  restartPolicy: OnFailure
